---
title: "model comparisons"
format: html
editor: visual
---

Models of lifetime sex partners with original sample, restricted sample, and heterosexual control

```{r partners}
lifetime_compare
```

Models of lifetime sex partners with original sample, restricted sample

```{r past year}
pastyear_compare
```

Models of lifetime sex partners with original sample, restricted sample

```{r age first sex}
agefirst_compare
```

Models of lifetime sex partners with original sample, restricted sample, and heterosexual control

```{r partnered}
partnered_compare
```

```{r figs}

# Figures -----------------------------------------------------------------



mvnames <- c(
  "Anthropometric", #baseline model has bmi
  "Socieoeconomic",
  "Health",
  "Physical Activity",
  "Hormone" #sub new model with sex centered testosterone
)

fig1h <- forestplot(
  m_lifetime_h, msoc1_h, mheal1_h, mphys1_h, mhor1_h,
  intercept = F,
  facet = F,
  dodgewidth = .8,
  modelnames = mvnames,
  varnames = vnames,
  size = 0.7,
  linewidth = 0.7) + theme_minimal() +
  theme(axis.text.y = element_text(size = 9), plot.title = element_text(size = 11)) +
  labs(title = "Lifetime Number of Sexual Partners (restricted to self-identified heterosexual)")


fig2h <- forestplot(
  m_pastyear_h, msoc2_h, mheal2_h, mphys2_h, mhor2_h,
  intercept = F,
  facet = F,
  dodgewidth = .8,
  modelnames = mvnames,
  varnames = vnames,
  size = 0.7,
  linewidth = 0.7
) + theme_minimal() +
  labs(title = "Past Year Number of Sexual Partners (restricted to self-identified heterosexual)")  +
  theme(axis.text.y = element_blank(), plot.title = element_text(size = 11))

fig3h <- forestplot(
  m_agefirst_h, msoc3_h, mheal3_h, mphys3_h, mhor3_h,
  intercept = F,
  facet = F,
  dodgewidth = .8,
  modelnames = mvnames,
  varnames = vnames,
  size = 0.7,
  linewidth = 0.7
) + theme_minimal() +
  labs(title = "Age at first sex (restricted to self-identified heterosexual)")  +
  theme(axis.text.y = element_blank(), plot.title = element_text(size = 11))

fig4h <- forestplot(
  m_partnered_h, msoc4_h, mheal4_h, mphys4_h, mhor4_h,
  intercept = F,
  facet = F,
  dodgewidth = .8,
  modelnames = mvnames,
  varnames = vnames,
  size = 0.7,
  linewidth = 0.7
) + theme_minimal() +
  labs(title = "Currently partnered (restricted to self-identified heterosexual)")  +
  theme(axis.text.y = element_blank(), plot.title = element_text(size = 11))


#same models not restricted to heterosexual
fig1 <- forestplot(
  m_lifetime, msoc1, mheal1, mphys1, mhor1,
  intercept = F,
  facet = F,
  dodgewidth = .8,
  modelnames = mvnames,
  varnames = vnames,
  size = 0.7,
  linewidth = 0.7) + theme_minimal() +
  theme(axis.text.y = element_text(size = 9), plot.title = element_text(size = 11)) +
  labs(title = "Lifetime Number of Sexual Partners")


fig2 <- forestplot(
  m_pastyear, msoc2, mheal2, mphys2, mhor2,
  intercept = F,
  facet = F,
  dodgewidth = .8,
  modelnames = mvnames,
  varnames = vnames,
  size = 0.7,
  linewidth = 0.7
) + theme_minimal() +
  labs(title = "Past Year Number of Sexual Partners")  +
  theme(axis.text.y = element_text(size = 9), plot.title = element_text(size = 11))


fig3 <- forestplot(
  m_agefirst, msoc3, mheal3, mphys3, mhor3,
  intercept = F,
  facet = F,
  dodgewidth = .8,
  modelnames = mvnames,
  varnames = vnames,
  size = 0.7,
  linewidth = 0.7
) + theme_minimal() +
  labs(title = "Age at first sex")  +
  theme(axis.text.y = element_text(size = 9), plot.title = element_text(size = 11))

fig4 <- forestplot(
  m_partnered, msoc4, mheal4, mphys4, mhor4,
  intercept = F,
  facet = F,
  dodgewidth = .8,
  modelnames = mvnames,
  varnames = vnames,
  size = 0.7,
  linewidth = 0.7
) + theme_minimal() +
  labs(title = "Currently partnered")  +
  theme(axis.text.y = element_text(size = 9), plot.title = element_text(size = 11))

compare_any <- (fig1 + fig1h) + plot_layout(guides = "collect", ncol = 2) & theme(legend.position = "bottom")
compare_any

compare_pastyear <- (fig2 + fig2h) + plot_layout(guides = "collect", ncol = 2) & theme(legend.position = "bottom")
compare_pastyear

compare_agefirst <- (fig3 + fig3h) + plot_layout(guides = "collect", ncol = 2) & theme(legend.position = "bottom")
compare_agefirst

compare_partnered <- (fig4 + fig4h) + plot_layout(guides = "collect", ncol = 2) & theme(legend.position = "bottom")
compare_partnered


```
